name: tree_collection
version: 0.6.0
description: A dart package that help works with tree structure
repository: https://github.com/wondertalik/tree_collection

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12